### ISSUE TITLE
questions on metric of result

### ISSUE THREAD

**Issue by wpj2018** [ibalazevic/HypER#2]
I have two questions:
First:   when i change the code "d = Data(data_dir=data_dir, **reverse=True**)" in hyper.py to "d = Data(data_dir=data_dir, **reverse=False**)", the result is worse.

the result of FB15k is:
300
0.0010843060445040464
Validation:
Number of data points: 50000
Hits @10: 0.79446
Hits @3: 0.68082
Hits @1: 0.51768
Mean rank: 107.91348
Mean reciprocal rank: 0.6174073599114973
Test:
Number of data points: 59071
Hits @10: 0.7901169778740837
Hits @3: 0.6757630647864434
Hits @1: 0.509437795195612
Mean rank: 106.1193309745899
Mean reciprocal rank: 0.6112205864139554

Second: you metric only consider one direction, that is you calculate the "hit@10 hit@3 hit@1" only using head entity（tail entity） and relation to predict tail entity (head entity). Shouldn't you consider the mean value of metric of two direction?

**Comment by ibalazevic** [comment]
Sorry for the delayed response. 

Actually, the responses to both of your questions are related. We train the model the same way as in Dettmers et al., 2018 (also see [here](https://github.com/TimDettmers/ConvE)): for each relation, we create an inverse by appending "_reverse" to the relation name. That way we are able to train and test only in one direction (desirable due to 1-N scoring), predicting both head and tail, because our dataset doesn't just contain (e_1, r, e_2), but elso (e_2, r_reverse, e_1).

Hope this makes things clearer.
